version: 0.2
phases:
  pre_build:
    commands:
      - npm install --prefix react
      - echo "VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY" > react/.env
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run --prefix react build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "react/dist"
