AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Instance with access to S3 buckets

Parameters:
  GithubUsername:
    Type: String
    Default: zmunk
    AllowedPattern: "[A-Za-z0-9-]+"
  GithubRepo:
    Type: String
    Default: auto-deploy-test
    AllowedPattern: "[A-Za-z0-9-]+"
  GithubBranch:
    Type: String
    Default: main
    AllowedPattern: "[A-Za-z0-9-]+"
  GithubOAuthToken:
    Type: String
    NoEcho: true
    AllowedPattern: '[A-Za-z0-9_]*'

Resources:

  ##########
  #   S3   #
  ##########

  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${ReactAppBucket}/*"

  ##################
  #   CloudFront   #
  ##################

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt ReactAppBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        Enabled: true


  #################
  #   CodeBuild   #
  #################

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: CodeBuildCICDAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${ReactAppBucket}/*
                  - !Sub arn:aws:s3:::${ReactAppBucket}
              - Effect: Allow  
                Action:
                  - "codepipeline:CreateWebhook"
                  - "codepipeline:DeleteWebhook"
                Resource: "*"                


  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: !Ref GithubOAuthToken


  ReactCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ReactCodeBuildProject-${AWS::StackName}
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GithubUsername}/${GithubRepo}.git 
        Auth:
          Type: OAUTH
          Resource: !Ref CodeBuildSourceCredential
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/main
      TimeoutInMinutes: 15


Outputs:
  CloudFrontDistributionDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFront Distribution Domain Name
  S3BucketName:
    Value: !Ref ReactAppBucket
    Description: 'The name of the created S3 bucket'
